### ISSUE TITLE
[GB] Super Mario Land graphic problem

### ISSUE THREAD

**Issue by puggile** [OtherCrashOverride/go-play#28] opened 2018-07-08 18:17 UTC
To reproduce issue:

Start a new game and go in the left of the screen then "Mario" goes under the background.
fw version: 20180702-psram

**Comment by OtherCrashOverride** [comment] 2018-07-09 00:32
Duplicate of #22.

If this issue persists after the next firmware update, please re-open this issue.

**Closed by OtherCrashOverride** 2018-07-09 00:32 UTC
